name: BoxTool
main: YoungRichNigger9\BoxTool\Main
version: 0.2
api: 2.0.0
author: YoungRichNigger9/HuaYoyu
load: "STARTUP"
description: "A tool box plugin for your server"
website: "https://github.com/YoungRichNigger9/BoxTool"
commands:
    afk:
        usage: /afk
        deacription: afk it!
    bthelp:
        usage: /bthelp
        description: Shows BoxTool Command list
    gms:
        usage: /gms
        description: Changes gamemode to Survival 
    gmc:
        usage: /gmc
        description: Changes gamemode to Creative
    gma:
        usage: /gma
        description: Changes gamemode to Adventure
    gmsp:
        usage: /gmsp
        description: Changes gamemode to Spectator
permissions:
    boxtool.afk:
        default: false
        description: Allows user to use /afk
    boxtool.gms:
        default: op
        description: Allows user to use /gms
    boxtool.gmc:
        default: op
        description: Allows user to use /gmc
    boxtool.gma:
        default: op
        description: Allows user to use /gma
    boxtool.gmsp:
        default: op
        description: Allows user to use /gmsp
