name: BoxTool
author: Francois284/HuaYoyu
api:  2.0.0
version: Soon
description: "A tool box plugin for your server"
main: BoxTool/plugin
website:
commands:
    bthelp:
        usage: /bthelp
        description: Shows BoxTool Command list
    gs:
        usage: /gs
        description: Changes gamemode to Survival 
    gc:
        usage: /gc
        description: Changes gamemode to Creative
    ga:
        usage: /ga
        description: Changes gamemode to Adventure
    gsp:
        usage: /gsp
        description: Changes gamemode to Spectator
permissions:
    boxtool.gs:
        default: op
        description: Allows use of /gs
    boxtool.gc:
        default: op
        description: Allows use of /gc
    boxtool.ga:
        default: op
        description: Allows use of /ga
    boxtool.gsp:
        default: op
        description: Allows use of /gsp
